### ISSUE TITLE
Is there documentation?

### ISSUE THREAD

**Issue by JesseTG** [nkthiebaut/zeugma#1]
I'm playing around with different word-embedding loaders.  Is there documentation available for this one?

**Comment by nkthiebaut** [comment]
Hello Jesse,

I haven't generated the documentation yet but I plan to do it in the coming weeks. In the meantime please tell me if you have any specific question.

Nicolas

**Comment by JesseTG** [comment]
No specific question as of yet, I just wanted to be able to thumb through something before trying it out.  Thank you, though.

**Comment by nkthiebaut** [comment]
Hey Jesse, just wanted to let you know that I've created a documentation (https://zeugma.readthedocs.io/). I still have to improve it but I'll add details and examples on a regular basis.
