### ISSUE TITLE
Error when install zeugma

### ISSUE THREAD

**Issue by hashmiuk** [nkthiebaut/zeugma#17]
Hello, am facing the following error when am installing zeugma
pip install zeugma 

Collecting zeugma
  Using cached zeugma-0.46.tar.gz (7.2 kB)
Note: you may need to restart the kernel to use updated packages.
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\space\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-cnkvoo1g\\zeugma\\setup.py'"'"'; __file__='"'"'C:\\Users\\space\\AppData\\Local\\Temp\\pip-install-cnkvoo1g\\zeugma\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\space\AppData\Local\Temp\pip-pip-egg-info-4m8xro_z'
         cwd: C:\Users\space\AppData\Local\Temp\pip-install-cnkvoo1g\zeugma\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\space\AppData\Local\Temp\pip-install-cnkvoo1g\zeugma\setup.py", line 14, in <module>
        long_description=open("README.rst", "r").read(),
      File "C:\Users\space\anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1013: character maps to <undefined>
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nkthiebaut** [comment]
Hey Hashmiuk, thanks for the heads up.

I should have fixed the issue in my latest PR. Please install the latest version (0.48) and let me know if you still encounter problems.

**Comment by hashmiuk** [comment]
Thank you very much, it is working fine.
