### ISSUE TITLE
Issues with Gensim 4.0.0

### ISSUE THREAD

**Issue by svengiegerich** [nkthiebaut/zeugma#21]
I tried to run the basic example of zeugma, but it seems like `zeugma` has an issue with the newest version of `gensim 4.0.0`--at least for 'fastText'?

 I try to run `embeddings = fastText.transform(['what is zeugma', 'a figure of speech'])` and get the following error:

> AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
> Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
> See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

and

> ~/.local/lib/python3.7/site-packages/zeugma/embeddings.py in <lambda>(x)
>      74                     )
>      75                 raw_tokens = raw_text.split()
> ---> 76             return list(filter(lambda x: x in self.model.vocab, raw_tokens))
>      77 
>      78         tokens = preprocess_text(text)

Unfortunately, I need the newest `gensim` version elsewhere. Is there any workaround to get `zeugma` going?

**Comment by seanbenhur** [comment]
have you solved the issue!? or is that works by downgrading zeugma!?

**Comment by KevinH45** [comment]
I've gotten this issue as well.

**Comment by nkthiebaut** [comment]
Hello, thanks for pointing it out I'll look into it tomorrow. 

According to the error message from Gensim it could be an easy fix. I'll keep you posted.
