### ISSUE TITLE
How to change the default download directory

### ISSUE THREAD

**Issue by kb-open** [nkthiebaut/zeugma#28]
Where does the model get downloaded when a call such as EmbeddingTransformer('glove') is made? And how can the default path be changed?

**Comment by nkthiebaut** [comment]
Under the hood, the `EmbeddingTransformer` uses `gensim.downloader.load`, which means that you can specify the default path by setting the `GENSIM_DATA_DIR` environment variable ([source](https://radimrehurek.com/gensim/downloader.html)).
